--- 
output_dir: output
data_sources: 
- type: filesystem_unified
  items_root: /
  layouts_root: /

# Custom settings

text_extensions: [ 'html', 'css', 'haml', 'sass', 'scss', 'erb', 'md', 'textile', 'org', 'coffee' ]

deploy:
  default:
    provider:              aws
    bucket:                martinowen.net
    aws_access_key_id:     ENV['AWS_ACCESS_KEY_ID']
    aws_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']

# domain to which this site is deployed
base_url: http://martinowen.net

google_analytics:
  domain: martinowen.net
  site_id: UA-3614897-1

# currently used by logo
site_name: Martin Owen

# number of full featured posts to display on front
featured_count: 0

# number of excerpted posts to display on front
excerpt_count: 10

# number of other articles to reference at bottom of each article
other_articles_max: 3

# DISQUS Site Shortname. Comment out to disable.
disqus_shortname: martinowen
