source :gemcutter

gem "nanoc", "3.3.1"
gem "rack"
gem "rack-rewrite", :require => "rack/rewrite"
gem "rake"
gem "mime-types"
gem "cri"
gem "haml"
gem "rdiscount"
gem "builder"
gem "activesupport"
gem "RedCloth"
gem "coderay"
gem "nokogiri"
gem "adsf"
gem "compass"
gem "compass-960-plugin"
gem "org-ruby", "~> 0.5.3"
gem "spox-ultraviolet"
gem "typogruby"
gem "coffee-script", "~> 2.2.0"
