source :gemcutter

gem "nanoc"
gem "rack"
gem "rack-rewrite", :require => "rack/rewrite"
gem "rake"
gem "mime-types"
gem "cri"
gem "haml"
gem "rdiscount"
gem "builder"
gem "activesupport"
gem "RedCloth"
gem "coderay"
gem "nokogiri"
gem "adsf"
gem "compass"
gem "compass-960-plugin"
gem "org-ruby"
gem "spox-ultraviolet"
gem "typogruby"
gem "coffee-script"
gem "pygments.rb"
