---
created_at: 2013/08/30
excerpt: Since reading Windows PowerShell for Developers, I've been seriously impressed!
kind: article
publish: false
tags: [powershell, .net]
title: Exploring PowerShell
---
* Overcoming my PowerShell cynicism

I've always loved Unix shells for their simplicity and power. I was sure that PowerShell was nothing in comparison, just an iteration of Windows batch files or VBScript (two of the most unfriendly scripting environments).

I recently read the excellent book [[http://shop.oreilly.com/product/0636920024491.do][Windows PowerShell for Developers]] by Douglas Finke. If you are a .NET developer I highly recommend this book. Douglas gives a really good introduction to PowerShell and also highlights how PowerShell's integration with the .NET framework can enable you to explore APIs at the console.

* PowerShell = ObjectShell

What really blew me away about PowerShell is the pipeline. Unix piping always felt really elegant, but PowerShell improves on it by piping objects rather than streams. This is why I think Microsoft chose the wrong name - I think ObjectShell would have been more appropriate.

Add to the object piping great CSV, XML (and in PowerShell 3.0 JSON) importing and exporting commands, and you've got a very nice glue language indeed.

The example below allows me to get a very simple command line view of the new messages in my GMail inbox:

#+BEGIN_SRC powershell
function List-Mail {
    $GmailFeed = "https://mail.google.com/mail/feed/atom"
    $SecurePassword = ConvertTo-SecureString "password123" -AsPlainText -Force
    $Credential = New-Object System.Management.Automation.PSCredential ("billy@gmail.com", $SecurePassword)

    Invoke-RestMethod -Uri $GmailFeed -Credential $Credential | % {
        [PSCustomObject] @{
            Time = Get-Date -Date $_.issued -Format "ddd HH:mm"
            From = $_.author.name
            Title = $_.title
        }
    } | Format-Table -AutoSize
}
#+END_SRC

This lets me see if my mail is worth opening in the browser without distracting me too much.
